application:
  actions: actions
  runtimeManifest:
    packages:
      mailgun:
        license: Apache-2.0
        actions:
          sendmail:
            function: actions/mailgun/sendmail.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              MAILGUN_API_KEY: ${MAILGUN_API_KEY}
              GCAPTCHA_SECRET: ${GCAPTCHA_SECRET}
            annotations:
              require-adobe-auth: false
              final: true
