name: AIO Mailgun deploy 99brand to production

on:
  push:
    branches:
      - 77-email
      - master
defaults:
  run:
    working-directory: tools/contact-form/mailgun
jobs:
  deploy:
    name: Deploy AIO Mailgun to 99brandparty production
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['14']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.0.0
        with:
          os: ${{ matrix.os }}
      - name: Build
        uses: adobe/aio-apps-action@1.0.0
        env:
          aio_ns_prod: ${{ secrets.AIO_RUNTIME_NAMESPACE_PROD }}  
        with:
          os: ${{ matrix.os }}
          command: build
          AIO_RUNTIME_NAMESPACE: $aio_ns_prod
      - name: Deploy
        uses: adobe/aio-apps-action@1.0.0
        env:
          aio_auth_prod: ${{ secrets.AIO_RUNTIME_AUTH_PROD }}  
          aio_ns_prod: ${{ secrets.AIO_RUNTIME_NAMESPACE_PROD }}  
          mailgun_prod: ${{ secrets.MAILGUN_API_KEY }}  
          captcha_prod: ${{ secrets.GCAPTCHA_SECRET }}  
        with:
          os: ${{ matrix.os }}
          command: deploy
          AIO_RUNTIME_AUTH: $aio_auth_prod
          AIO_RUNTIME_NAMESPACE: $aio_ns_prod
          MAILGUN_API_KEY: $mailgun_prod
          GCAPTCHA_SECRET: $captcha_prod