name: AIO Mailgun deploy 99brand to production

on:
  push:
    branches:
      - 77-email
      - master
defaults:
  run:
    working-directory: tools/contact-form/mailgun
jobs:
  deploy:
    name: Deploy AIO Mailgun to 99brandparty production
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['14']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.0.0
        with:
          os: ${{ matrix.os }}
      - name: Build
        uses: adobe/aio-apps-action@1.0.0
        with:
          os: ${{ matrix.os }}
          command: build
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_PROD }}
      - name: Deploy
        uses: adobe/aio-apps-action@1.0.0
        with:
          os: ${{ matrix.os }}
          command: deploy
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_PROD }}
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_PROD }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          GCAPTCHA_SECRET: ${{ secrets.GCAPTCHA_SECRET }}